### ISSUE TITLE
Create little test programs to display chunks/quads

### ISSUE THREAD

**Issue by kingussopp** [7map/7map#11]
a chunk is a small piece of the entire map that may be loaded/unloaded on demand

Advancement : 
- [x] @kingussopp 
- [x] @l3alr0g 
- [x] @Mmzhk21

**Comment by l3alr0g** [comment]
I've created a simple test app that currently doesn't run because it isn't quite finished, but should still give you guys a quick overview of how I think we should use the LWJGL framework (in terms of code structure).

**Comment by l3alr0g** [comment]
@7map/rendering when you finish working on an issue that has been assigned to multiple people in the team, you can check the box next to your name in the issue content, this will show up in the project as a progress bar, which is neat but also very useful to track an issue's advancement 
![Screenshot from 2021-04-04 18-56-55](https://user-images.githubusercontent.com/46868627/113515899-8d590380-9577-11eb-9133-885257c27615.png)
Me and @seba1204 are planning on writing a short markdown Q/A file which would contain all the questions you might be asking yourself when it comes to github features and conventions
