### ISSUE TITLE
test out features provided by the LWJGL 3 framework

### ISSUE THREAD

**Issue by l3alr0g** [7map/7map#2]
Read the documentation @ https://www.lwjgl.org/guide 
understand it and create a couple of test applications to get the hang of it.

**Comment by l3alr0g** [comment]
Dat party be lit yo @kingussopp can't deny that

**Comment by kingussopp** [comment]
Feels like heaven in fact 😍

**Comment by l3alr0g** [comment]
Choo choo motherf*cker

**Comment by l3alr0g** [comment]
let's keep this thread professional shall we

**Comment by l3alr0g** [comment]
okay @7map/rendering  so I here's what I found when it comes to UI stuff and displaying buttons/search bars on top of the openGL rendering zone : https://github.com/ThemableWidgetLibrary/twl
let me know what you think. Still learning how to actually use GL because it clearly isn't as easy as I thought it would be.
Oh and a quick reminder, we're having a meeting on monday so PLEASE be somewhat ready.

**Comment by kingussopp** [comment]
Shall we fix the hour of the meeting ,because we have classes until 17h30 so I suggest that we meet at 19h00

**Comment by l3alr0g** [comment]
Yes that would be great. 19:00 it is then

**Comment by kingussopp** [comment]
@l3alr0g what is our use of "main.yml" that you have just uploaded ?

**Comment by l3alr0g** [comment]
it's a workflow configuration file, used by github to automate some tasks. At the moment I have configured it to automatically assign any issue to the Global Feature progress project

**Comment by l3alr0g** [comment]
by the way, off topic questions (not related to the issue) should be posted in the team's discussion : https://github.com/orgs/7map/teams/rendering/discussions
