### ISSUE TITLE
Personnal event handler

### ISSUE THREAD

**Issue by seba1204** [7map/7map#28]
Dans le but de faciliter et rendre plus propre la programmation des évènements liés aux interractions utilisateurs, il serait sympa de se faire notre propre handler.
Voilà comment à quoi il pourrait ressembler  :
```java
window.onEvent(Event.MOVE, (dx, dy) -> { });
window.onEvent(Event.ZOOM, (delta) -> { });
```
Les évènements `Event.MOVE` et `Event.ZOOM` peuvent par exemple être en dur dans un enum, ou plus dynamiquement dans une HashMap. On pourrait imaginer pourvoir faire évoluer l'API avec d'autres évènements comme `Event.GetFocus`, `Event.LostFocus`, ... à moins qu'il y ait d'autres endroits plus pertinents pour ça.

Il faudrait aussi que le callback renvoit des paramètres pertinents en fonction de l'évènement, quitte à créer un objet de retour exprès (comme vu en TD).

**Comment by l3alr0g** [comment]
le handler d'évènements n'a pas encore été codé, je laisse l'issue ouverte pour le moment a priori
